version: '3.7'
services:
  mappers:
     build:
        context: .
        dockerfile: mapperDockerFile
     image: mapper
     expose:
        - '6666'
        - '9090'
        - '8787'
        - '7777'
     entrypoint:
        - java
        - com.atypon.nodes.mappernode.MapperNode
     deploy:
        replicas: 1
  reducers:
     build:
        context: .
        dockerfile: reducerDockerFile
     image: reducer
     expose:
        - '6666'
        - '8787'
        - '9999'
        - '8789'
     entrypoint:
        - java
        - com.atypon.nodes.ReducerNode
     deploy:
        replicas: 1
     depends_on:
        - mappers
