version: '3.7'
services:
  mappers:
    build:
      context: .
      dockerfile: Dockerfile
    image: map_reduce
    expose:
      - '7777'
      - '8787'
      - '9090'
      - '6666'

    entrypoint: java -cp ../../../ com/atypon/nodes/MapperNode
    deploy:
      replicas: 4
  reducers:
    image: map_reduce
    expose:
      - '7777'
      - '9091'
      - '8787'
      - '9999'

    entrypoint: java -cp ../../../ com/atypon/nodes/ReducerNode
    deploy:
      replicas: 4
    depends_on:
      - mappers

