version: '3.7'
services:
  mappers:
    image: map_reduce
    expose:
      - '7777'
      - '8787'
      - '9090'
      - '6666'
  
    entrypoint: java -cp ../../../ com/atypon/nodes/MapperNode 192.168.8.102 7777
    deploy:
      replicas: 2

  reducers:
    image: map_reduce
    expose:
      - '7777'
      - '9091'
      - '8787'
  
    entrypoint: java -cp ../../../ com/atypon/nodes/ReducerNode 192.168.8.102 7777
    deploy:
      replicas: 2
    depends_on:
      - mappers

