version: '3.7'
services:
  forwarder:
    image: map_reduce
    ports:
      - target: 7676
        published: 7676
        protocol: tcp
        mode: host
    entrypoint: java -cp ../../../ com/atypon/nodes/SwarmForwarderNode 192.168.8.102
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: global

  mappers:
    image: map_reduce
    ports:
      - target: 7777
        published: 7777
        mode: host
      - target: 8787
        published: 8787
        mode: host
      - target: 9090
        published: 9090
        mode: host
      - target: 6666
        published: 6666
        mode: host


    entrypoint: java -cp ../../../ com/atypon/nodes/MapperNode 192.168.99.130 7676
    deploy:
      placement:
        constraints: [node.labels.name == mapper]
      mode: global
      endpoint_mode: dnsrr
    depends_on:
      - forwarder

  reducers:
    image: map_reduce
    ports:
      - target: 7777
        published: 7777
        mode: host
      - target: 9091
        published: 9091
        mode: host
      - target: 8787
        published: 8787
        mode: host


    entrypoint: java -cp ../../../ com/atypon/nodes/ReducerNode 192.168.99.130 7676
    deploy:
      placement:
        constraints: [node.labels.name == reducer]
      mode: global
      endpoint_mode: dnsrr
    depends_on:
      - forwarder

networks:
  mynet1:
    driver: overlay
    attachable: true
